/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : LCD_SDA.h
**     Project     : LCD_GPIO
**     Processor   : MK64FX512VLQ12
**     Component   : BitIO_LDD
**     Version     : Component 01.033, Driver 01.03, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-06-12, 15:56, # CodeGen: 1
**     Abstract    :
**         The HAL BitIO component provides a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL BitIO API are simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : LCD_SDA
**          Pin for I/O                                    : ADC0_SE9/ADC1_SE9/PTB1/I2C0_SDA/FTM1_CH1/RMII0_MDC/MII0_MDC/FTM1_QD_PHB
**          Pin signal                                     : 
**          Direction                                      : Input/Output
**          Initialization                                 : 
**            Init. direction                              : Output
**            Init. value                                  : 0
**            Auto initialization                          : yes
**          Safe mode                                      : no
**     Contents    :
**         Init       - LDD_TDeviceData* LCD_SDA_Init(LDD_TUserData *UserDataPtr);
**         Deinit     - void LCD_SDA_Deinit(LDD_TDeviceData *DeviceDataPtr);
**         GetDir     - bool LCD_SDA_GetDir(LDD_TDeviceData *DeviceDataPtr);
**         SetDir     - void LCD_SDA_SetDir(LDD_TDeviceData *DeviceDataPtr, bool Dir);
**         SetInput   - void LCD_SDA_SetInput(LDD_TDeviceData *DeviceDataPtr);
**         SetOutput  - void LCD_SDA_SetOutput(LDD_TDeviceData *DeviceDataPtr);
**         GetVal     - bool LCD_SDA_GetVal(LDD_TDeviceData *DeviceDataPtr);
**         PutVal     - void LCD_SDA_PutVal(LDD_TDeviceData *DeviceDataPtr, bool Val);
**         ClrVal     - void LCD_SDA_ClrVal(LDD_TDeviceData *DeviceDataPtr);
**         SetVal     - void LCD_SDA_SetVal(LDD_TDeviceData *DeviceDataPtr);
**         NegVal     - void LCD_SDA_NegVal(LDD_TDeviceData *DeviceDataPtr);
**         ConnectPin - LDD_TError LCD_SDA_ConnectPin(LDD_TDeviceData *DeviceDataPtr);
**         GetRawVal  - bool LCD_SDA_GetRawVal(LDD_TDeviceData *DeviceDataPtr);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file LCD_SDA.h
** @version 01.03
** @brief
**         The HAL BitIO component provides a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL BitIO API are simpler and more
**         portable to various microprocessors.
*/         
/*!
**  @addtogroup LCD_SDA_module LCD_SDA module documentation
**  @{
*/         

#ifndef __LCD_SDA_H
#define __LCD_SDA_H

/* MODULE LCD_SDA. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "IO_Map.h"
#include "GPIO_PDD.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 



/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define LCD_SDA_PRPH_BASE_ADDRESS  0x400FF040U
  
/*! Device data structure pointer used when auto initialization property is enabled. This constant can be passed as a first parameter to all component's methods. */
#define LCD_SDA_DeviceData  ((LDD_TDeviceData *)PE_LDD_GetDeviceStructure(PE_LDD_COMPONENT_LCD_SDA_ID))

/* Methods configuration constants - generated for all enabled component's methods */
#define LCD_SDA_Init_METHOD_ENABLED    /*!< Init method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_Deinit_METHOD_ENABLED  /*!< Deinit method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_GetDir_METHOD_ENABLED  /*!< GetDir method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_SetDir_METHOD_ENABLED  /*!< SetDir method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_SetInput_METHOD_ENABLED /*!< SetInput method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_SetOutput_METHOD_ENABLED /*!< SetOutput method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_GetVal_METHOD_ENABLED  /*!< GetVal method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_PutVal_METHOD_ENABLED  /*!< PutVal method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_ClrVal_METHOD_ENABLED  /*!< ClrVal method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_SetVal_METHOD_ENABLED  /*!< SetVal method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_NegVal_METHOD_ENABLED  /*!< NegVal method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_ConnectPin_METHOD_ENABLED /*!< ConnectPin method of the component LCD_SDA is enabled (generated) */
#define LCD_SDA_GetRawVal_METHOD_ENABLED /*!< GetRawVal method of the component LCD_SDA is enabled (generated) */

/* Definition of implementation constants */
#define LCD_SDA_MODULE_BASE_ADDRESS PTB_BASE_PTR /*!< Name of macro used as the base address */
#define LCD_SDA_PORTCONTROL_BASE_ADDRESS PORTB_BASE_PTR /*!< Name of macro used as the base address */
#define LCD_SDA_PORT_MASK 0x02U        /*!< Mask of the allocated pin from the port */



/*
** ===================================================================
**     Method      :  LCD_SDA_Init (component BitIO_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the "Enable
**         in init. code" is set to "yes" value then the device is also
**         enabled(see the description of the Enable() method). In this
**         case the Enable() method is not necessary and needn't to be
**         generated. 
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* LCD_SDA_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_Deinit (component BitIO_LDD)
*/
/*!
**     @brief
**          Deinitializes the device. Switches off the device, frees
**         the device data structure memory, interrupts vectors, etc.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void LCD_SDA_Deinit(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_GetDir (component BitIO_LDD)
*/
/*!
**     @brief
**         Returns the selected direction.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Possible values:
**                           <false> - Input
**                           <true> - Output
*/
/* ===================================================================*/
bool LCD_SDA_GetDir(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_SetDir (component BitIO_LDD)
*/
/*!
**     @brief
**         Sets a pin direction (available only if the direction =
**         _[input/output]_).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Dir             - Direction to set. Possible values:
**                           <false> - Input
**                           <true> - Output
*/
/* ===================================================================*/
void LCD_SDA_SetDir(LDD_TDeviceData *DeviceDataPtr, bool Dir);

/*
** ===================================================================
**     Method      :  LCD_SDA_SetInput (component BitIO_LDD)
*/
/*!
**     @brief
**         Sets a pin direction to input (available only if the
**         direction = _[input/output]_).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void LCD_SDA_SetInput(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_SetOutput (component BitIO_LDD)
*/
/*!
**     @brief
**         Sets a pin direction to output (available only if the
**         direction = _[input/output]_).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
*/
/* ===================================================================*/
void LCD_SDA_SetOutput(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_GetVal (component BitIO_LDD)
*/
/*!
**     @brief
**         Returns the input/output value. If the direction is [input]
**         then the input value of the pin is read and returned. If the
**         direction is [output] then the last written value is read
**         and returned (see <Safe mode> property for limitations).
**         This method cannot be disabled if direction is [input].
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Input or output value. Possible values:
**                           <false> - logical "0" (Low level)
**                           <true> - logical "1" (High level)
*/
/* ===================================================================*/
bool LCD_SDA_GetVal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_GetRawVal (component BitIO_LDD)
*/
/*!
**     @brief
**         Method returns the input value of the pin. The method uses
**         raw data input register, i.e., a register that always reads
**         back the status of the pin regardless of the pin’s direction.
**         The method is available only if raw data input is supported
**         on the pin.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure returned by <Init> method.
**     @return
**                         - Input value. Possible values:
**                           <false> - logical "0" (Low level)
**                           <true> - logical "1" (High level)
*/
/* ===================================================================*/
bool LCD_SDA_GetRawVal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_PutVal (component BitIO_LDD)
*/
/*!
**     @brief
**         The specified output value is set. If the direction is <b>
**         input</b>, the component saves the value to a memory or a
**         register and this value will be written to the pin after
**         switching to the output mode (using <tt>SetDir(TRUE)</tt>;
**         see <a href="BitIOProperties.html#SafeMode">Safe mode</a>
**         property for limitations). If the direction is <b>output</b>,
**         it writes the value to the pin. (Method is available only if
**         the direction = <u><tt>output</tt></u> or <u><tt>
**         input/output</tt></u>).
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @param
**         Val             - Output value. Possible values:
**                           <false> - logical "0" (Low level)
**                           <true> - logical "1" (High level)
*/
/* ===================================================================*/
void LCD_SDA_PutVal(LDD_TDeviceData *DeviceDataPtr, bool Val);

/*
** ===================================================================
**     Method      :  LCD_SDA_ClrVal (component BitIO_LDD)
*/
/*!
**     @brief
**         Clears (set to zero) the output value. It is equivalent to
**         the [PutVal(FALSE)]. This method is available only if the
**         direction = _[output]_ or _[input/output]_.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure returned by <Init> method.
*/
/* ===================================================================*/
void LCD_SDA_ClrVal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_SetVal (component BitIO_LDD)
*/
/*!
**     @brief
**         Sets (to one) the output value. It is equivalent to the
**         [PutVal(TRUE)]. This method is available only if the
**         direction = _[output]_ or _[input/output]_.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure returned by <Init> method.
*/
/* ===================================================================*/
void LCD_SDA_SetVal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_NegVal (component BitIO_LDD)
*/
/*!
**     @brief
**         Negates (inverts) the output value. It is equivalent to the
**         [PutVal(!GetVal())]. This method is available only if the
**         direction = _[output]_ or _[input/output]_.
**     @param
**         DeviceDataPtr   - Pointer to device data
**                           structure returned by <Init> method.
*/
/* ===================================================================*/
void LCD_SDA_NegVal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  LCD_SDA_ConnectPin (component BitIO_LDD)
*/
/*!
**     @brief
**         This method reconnects the selected pin for this component.
**         This method is available only for the CPU derivatives and
**         peripherals that support the runtime pin sharing with other
**         internal on-chip peripherals.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by <Init> method.
**     @return
**                         - Error code, possible values:
**                           ERR_OK - OK
*/
/* ===================================================================*/
LDD_TError LCD_SDA_ConnectPin(LDD_TDeviceData *DeviceDataPtr);

/* END LCD_SDA. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __LCD_SDA_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.4 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
